version: '3.7'

services:
   app:
      build: .
      ports:
         - 8080:8080
      pid: host
      environment:
         LOG_ENV: dev
         LOG_APP: Stackify
         LOG_LEVEL: DEBUG
      volumes:
         - /usr/local/stackify:/usr/local/stackify
         